server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://110.40.224.64:3306/es?useSSL=false
    username: root
    password: eric
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 120.26.107.127
    port: 5672
    username: eric
    password: 1234
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
