server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://110.40.224.64:3306/cache?useSSL=false
    username: eric
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.26.107.127
mybatis-plus:
  type-aliases-package: com.heima.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.heima: debug
  pattern:
    dateformat: HH:mm:ss:SSS
canal:
  destination: eric
  server: 110.40.224.64:11111
